name: proyecto_app_mobiles
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  card_swiper: 3.0.1
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  mvvm: ^0.5.2
  local_auth: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/imagenes/
